import { BackendBlueprint } from "@/features/architecture/types";

/**
 * Environment Variable Generator
 * Generates .env.example based on selected infrastructure.
 */
export class EnvGenerator {
  public static generate(blueprint: BackendBlueprint): string {
    let env = "# Generated by Simplicit\n\n";
    env += "PORT=3000\n";
    env += "NODE_ENV=development\n\n";

    const infra = blueprint.infrastructure;

    // Database
    env += "# Database\n";
    env += "DATABASE_URL=postgres://user:password@localhost:5432/dbname\n";
    if (infra.database.provider.toLowerCase().includes('supabase')) {
      env += "SUPABASE_URL=\n";
      env += "SUPABASE_ANON_KEY=\n";
      env += "SUPABASE_SERVICE_ROLE_KEY=\n";
    }
    env += "\n";

    // Auth
    env += "# Authentication\n";
    if (infra.auth.provider.toLowerCase().includes('clerk')) {
      env += "CLERK_PUBLISHABLE_KEY=\n";
      env += "CLERK_SECRET_KEY=\n";
    } else if (infra.auth.provider.toLowerCase().includes('lucia')) {
      env += "AUTH_SECRET=\n";
    }
    env += "\n";

    // Storage
    if (infra.storage.provider !== "Unknown") {
      env += "# Storage\n";
      if (infra.storage.provider.toLowerCase().includes('cloudinary')) {
        env += "CLOUDINARY_CLOUD_NAME=\n";
        env += "CLOUDINARY_API_KEY=\n";
        env += "CLOUDINARY_API_SECRET=\n";
      }
      env += "\n";
    }

    // Payments
    if (infra.payments.provider !== "Unknown") {
      env += "# Payments\n";
      if (infra.payments.provider.toLowerCase().includes('stripe')) {
        env += "STRIPE_SECRET_KEY=\n";
        env += "STRIPE_WEBHOOK_SECRET=\n";
      }
      env += "\n";
    }

    // Email
    if (infra.email.provider !== "Unknown") {
      env += "# Email\n";
      if (infra.email.provider.toLowerCase().includes('resend')) {
        env += "RESEND_API_KEY=\n";
      }
      env += "\n";
    }

    return env;
  }
}
