import { Project } from "@/lib/types";

/**
 * Project Exporter (Legacy Bridge)
 * Faithful deliverer of generated files. No templates, no leakage.
 */
export function generateProjectFiles(project: Project): Record<string, string> {
  const metadata = project.generation_metadata || {};
  
  // 1. Prefer deterministic files from the pipeline
  if (metadata.files && Object.keys(metadata.files).length > 0) {
    return metadata.files;
  }

  // 2. Fallback for legacy projects (Minimal only, no Hono/Express defaults)
  const files: Record<string, string> = {};
  
  if (metadata.schemaCode) {
    files["src/db/schema.ts"] = Array.isArray(metadata.schemaCode) 
      ? metadata.schemaCode.join("\n") 
      : metadata.schemaCode;
  }

  if (metadata.routeCode) {
    files["src/routes/api.ts"] = Array.isArray(metadata.routeCode)
      ? metadata.routeCode.join("\n")
      : metadata.routeCode;
  }

  // Mandatory project files if missing
  if (!files["README.md"]) {
    files["README.md"] = `# ${project.name}\n\nGenerated by Simplicit.`;
  }

  return files;
}
