import { Project } from "@/lib/types";

function slugify(text: string): string {
  return text
    .toString()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\w\-]+/g, "")
    .replace(/\-\-+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");
}

export function generateProjectFiles(project: Project): Record<string, string> {
  const metadata = project.generation_metadata || {};
  const stackSummary = metadata.stackSummary || {};
  const framework = stackSummary.framework || "Hono";
  const database = stackSummary.database || "PostgreSQL";
  const cache = stackSummary.cache || "Redis";
  const auth = stackSummary.auth || "Lucia";
  const payments = stackSummary.payments || "Stripe";

  const files: Record<string, string> = {};

  // 1. README.md
  let endpointsList = "";
  if (metadata.apiRoutes && Array.isArray(metadata.apiRoutes)) {
    endpointsList = metadata.apiRoutes
      .map((r: any) => `- **${r.method}** \`${r.path}\` ${r.auth ? `*(Auth: ${r.auth})*` : ""} - ${r.note || ""}`)
      .join("\n");
  } else {
    endpointsList = "- **GET** `/api/health` - Check health status\n- **GET** `/api/users` - Fetch user profiles";
  }

  const readmeContent = `# ${project.name}

Generated by **Simplicit** — an AI backend architect engine.

## Description
${project.prompt}

## Technology Stack
- **Framework**: ${framework}
- **Database**: ${database}
- **Cache/Session**: ${cache}
- **Authentication**: ${auth}
- **Payments**: ${payments}
- **Runtime**: Node.js + TypeScript

## Setup Instructions

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Configure environment variables:
   \`\`\`bash
   cp .env.example .env
   # Add your connection secrets to .env
   \`\`\`

3. Run migrations and seed database:
   \`\`\`bash
   npm run db:generate
   npm run db:migrate
   \`\`\`

4. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

## Designed API Endpoints
${endpointsList}
`;

  files["README.md"] = readmeContent;

  // 2. tsconfig.json
  files["tsconfig.json"] = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": ["src/**/*"]
}
`;

  // 3. package.json
  let frameworkDeps = '"hono": "^4.0.0",\n    "@hono/node-server": "^1.10.0"';
  if (framework.toLowerCase().includes("fastify")) {
    frameworkDeps = '"fastify": "^4.26.0"';
  } else if (framework.toLowerCase().includes("express")) {
    frameworkDeps = '"express": "^4.19.0",\n    "@types/express": "^4.17.21"';
  }

  files["package.json"] = `{
  "name": "${slugify(project.name)}",
  "version": "1.0.0",
  "description": "Backend foundation generated for: ${project.prompt.slice(0, 60).replace(/"/g, '\\"')}",
  "main": "src/index.ts",
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js",
    "db:generate": "drizzle-kit generate",
    "db:migrate": "drizzle-kit migrate"
  },
  "dependencies": {
    ${frameworkDeps},
    "drizzle-orm": "^0.33.0",
    "pg": "^8.12.0",
    "dotenv": "^16.4.5"
  },
  "devDependencies": {
    "typescript": "^5.5.4",
    "@types/node": "^20.14.9",
    "tsx": "^4.15.7",
    "drizzle-kit": "^0.24.2",
    "@types/pg": "^8.11.6"
  }
}
`;

  // 4. .env.example
  let envContent = "";
  if (metadata.envVariables && Array.isArray(metadata.envVariables)) {
    envContent = metadata.envVariables
      .map((e: any) => `# ${e.note || "Environment key"}\n${e.k}=${e.v}`)
      .join("\n\n");
  } else {
    envContent = `# Primary Database Connection\nDATABASE_URL=postgres://postgres:postgres@localhost:5432/db\n\n# Server Port\nPORT=3000`;
  }
  files[".env.example"] = envContent;

  // 5. database schema code (clean raw text from tags if highlighted, otherwise clean text)
  let schemaRawCode = "";
  if (metadata.schemaCode && Array.isArray(metadata.schemaCode)) {
    // Strip HTML tags if code is pre-highlighted in database
    schemaRawCode = metadata.schemaCode
      .map((line: string) => line.replace(/<[^>]*>/g, ""))
      .join("\n");
  } else {
    schemaRawCode = `// packages/db/schema.ts\nexport {};`;
  }
  files["src/db/schema.ts"] = schemaRawCode;

  // 6. routes implementation code
  let routesRawCode = "";
  if (metadata.routeCode && Array.isArray(metadata.routeCode)) {
    routesRawCode = metadata.routeCode
      .map((line: string) => line.replace(/<[^>]*>/g, ""))
      .join("\n");
  } else {
    routesRawCode = `// apps/api/src/modules/routes.ts\nexport {};`;
  }
  files["src/routes/routes.ts"] = routesRawCode;

  // 7. entry point index.ts based on framework
  let indexContent = "";
  if (framework.toLowerCase().includes("fastify")) {
    indexContent = `import Fastify from 'fastify';
import dotenv from 'dotenv';
import { router as apiRouter } from './routes/routes';

dotenv.config();

const fastify = Fastify({ logger: true });

// Health check
fastify.get('/health', async () => {
  return { status: 'ok', uptime: process.uptime() };
});

// Register routes
fastify.register(apiRouter, { prefix: '/api' });

const port = Number(process.env.PORT) || 3000;
const start = async () => {
  try {
    await fastify.listen({ port, host: '0.0.0.0' });
    console.log(\`Fastify server running on port \${port}\`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();
`;
  } else if (framework.toLowerCase().includes("express")) {
    indexContent = `import express from 'express';
import dotenv from 'dotenv';
import apiRouter from './routes/routes';

dotenv.config();

const app = express();
app.use(express.json());

// Log incoming requests
app.use((req, res, next) => {
  console.log(\`[\${new Date().toISOString()}] \${req.method} \${req.url}\`);
  next();
});

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', uptime: process.uptime() });
});

// API routes
app.use('/api', apiRouter);

const port = Number(process.env.PORT) || 3000;
app.listen(port, () => {
  console.log(\`Express server running on port \${port}\`);
});
`;
  } else {
    // Default Hono framework template
    indexContent = `import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { router as apiRouter } from './routes/routes';
import dotenv from 'dotenv';

dotenv.config();

const app = new Hono();

// Global request logger
app.use('*', async (c, next) => {
  console.log(\`[\${new Date().toISOString()}] \${c.req.method} \${c.req.url}\`);
  await next();
});

// Health check
app.get('/health', (c) => c.json({ status: 'ok', uptime: process.uptime() }));

// Mount API routes
app.route('/api', apiRouter);

const port = Number(process.env.PORT) || 3000;
console.log(\`Hono Server is running on port \${port}\`);

serve({
  fetch: app.fetch,
  port
});
`;
  }

  files["src/index.ts"] = indexContent;

  // 8. Auth Middleware Mock helper
  files["src/middleware/auth.ts"] = `import type { Request, Response, NextFunction } from 'express';

// Simulated requireAuth middleware resolving user roles and headers
export function requireAuth(role?: string) {
  return async (req: any, res: any, next: any) => {
    const authHeader = req.headers['authorization'] || '';
    if (!authHeader) {
      return res ? res.status(401).json({ error: 'Unauthorized' }) : { status: 401 };
    }
    
    // Simulate user payload from token
    req.user = {
      id: 'usr_mock_001',
      email: 'user@acmestudio.com',
      role: role || 'student'
    };
    
    if (next) next();
  };
}
`;

  return files;
}
