import { BackendBlueprint, BlueprintEntity } from "@/features/architecture/types";

/**
 * Agent 6 — SDK Generator
 * Runs last, after Agent 5. Fully deterministic — zero LLM calls, template
 * logic only. Emits a typed frontend client for the generated backend:
 *
 *   api-client.ts      — typed fetch wrapper, one method per route
 *   src/types/api.ts   — request/response types derived from the blueprint
 *   .env.production    — deployment URL placeholder + required env var names
 *
 * Routes mirror what the backend actually serves: resource segments come from
 * entity.tableName (the same value ApiSurfaceCompiler uses), update routes are
 * PATCH (the generated controllers compile @Patch, not @Put), and non-primary
 * entities expose list+create only (matching NestJSGenerator.isRouteEnabled).
 *
 * The only throw is the tagged "SDKError:" guard for an entity-less blueprint.
 */

export interface SDKGeneratorInput {
  blueprint: BackendBlueprint;
  filesWithTests: Map<string, string>; // complete file map from Agent 5
  deploymentUrl?: string; // e.g. "https://my-app.railway.app" — optional at this stage
}

export interface SDKGeneratorOutput {
  allFiles: Map<string, string>; // filesWithTests + 3 new SDK files
  sdkFiles: {
    apiClient: string; // content of api-client.ts
    apiTypes: string; // content of src/types/api.ts
    envProduction: string; // content of .env.production
  };
}

interface EntityFieldDef {
  name: string;
  tsType: string; // 'string' | 'number' | 'boolean' | 'string | null' etc.
  optional: boolean;
}

interface RouteDefinition {
  // PATCH instead of the planned PUT — the generated NestJS controllers serve @Patch.
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string; // e.g. '/users' or '/users/:id'
  fnName: string; // e.g. 'getUsers' or 'getUserById'
  hasBody: boolean; // POST and PATCH have request bodies
  hasParam: boolean; // routes with :id
  entityName: string; // for type references
}

const TIMESTAMP_FIELDS = new Set(["id", "createdat", "updatedat"]);

export class SDKGenerator {
  execute(input: SDKGeneratorInput): SDKGeneratorOutput {
    if (!input.blueprint.entities || input.blueprint.entities.length === 0) {
      throw new Error("SDKError: blueprint has no entities — cannot generate API client");
    }

    const apiTypes = this.generateApiTypes(input.blueprint);
    const apiClient = this.generateApiClient(input.blueprint, input.deploymentUrl);
    const envProduction = this.generateEnvProduction(input.blueprint, input.deploymentUrl);

    const allFiles = new Map(input.filesWithTests);
    allFiles.set("api-client.ts", apiClient);
    allFiles.set("src/types/api.ts", apiTypes);
    allFiles.set(".env.production", envProduction);

    return {
      allFiles,
      sdkFiles: { apiClient, apiTypes, envProduction },
    };
  }

  // ── src/types/api.ts ───────────────────────────────────────────────

  private generateApiTypes(blueprint: BackendBlueprint): string {
    const sections: string[] = [];

    sections.push(`// Generated by Simplicit — typed API contracts for the generated backend.
// Mirrors the Drizzle schema types (uuid/varchar/text → string, integer → number,
// timestamp → ISO string, jsonb → Record<string, unknown>).

export interface ApiResponse<T> {
  data: T;
  message?: string;
  error?: string;
}`);

    for (const entity of blueprint.entities) {
      const name = this.entityTypeName(entity);
      const fields = this.getEntityFields(entity);
      const dtoFields = fields.filter((f) => !TIMESTAMP_FIELDS.has(f.name.toLowerCase()));

      // Read shape: id + timestamps always present, then the entity's own fields.
      const readLines: string[] = [];
      if (!fields.some((f) => f.name.toLowerCase() === "id")) readLines.push("  id: string;");
      for (const f of fields) {
        readLines.push(`  ${f.name}${f.optional ? "?" : ""}: ${f.tsType};`);
      }
      if (!fields.some((f) => f.name.toLowerCase() === "createdat")) readLines.push("  createdAt: string;");
      if (!fields.some((f) => f.name.toLowerCase() === "updatedat")) readLines.push("  updatedAt: string;");
      if (fields.length === 0) readLines.push("  [key: string]: unknown;");

      sections.push(`export interface ${name} {\n${readLines.join("\n")}\n}`);

      // Create DTO: fields without id/timestamps, required.
      const createLines = dtoFields.length > 0
        ? dtoFields.map((f) => `  ${f.name}: ${f.tsType};`)
        : ["  [key: string]: unknown;"];
      sections.push(`export interface Create${name}Dto {\n${createLines.join("\n")}\n}`);

      // Update DTO: same fields, all optional.
      const updateLines = dtoFields.length > 0
        ? dtoFields.map((f) => `  ${f.name}?: ${f.tsType};`)
        : ["  [key: string]: unknown;"];
      sections.push(`export interface Update${name}Dto {\n${updateLines.join("\n")}\n}`);
    }

    return sections.join("\n\n") + "\n";
  }

  // ── api-client.ts ──────────────────────────────────────────────────

  private generateApiClient(blueprint: BackendBlueprint, _deploymentUrl?: string): string {
    const usedTypes = new Set<string>(["ApiResponse"]);
    const methods: string[] = [];

    for (const entity of blueprint.entities) {
      const name = this.entityTypeName(entity);
      const routes = this.deriveRoutes(entity, blueprint);

      for (const route of routes) {
        usedTypes.add(name);
        if (route.method === "POST") usedTypes.add(`Create${name}Dto`);
        if (route.method === "PATCH") usedTypes.add(`Update${name}Dto`);
        methods.push(this.renderClientMethod(route, name));
      }
    }

    return `import type { ${Array.from(usedTypes).join(", ")} } from './src/types/api';

// Generated by Simplicit — typed fetch client for the generated backend.
// Usage: const api = createApiClient(process.env.NEXT_PUBLIC_API_URL!);

export class ApiClient {
  constructor(private readonly baseUrl: string) {}

${methods.join("\n\n")}
}

export function createApiClient(baseUrl: string): ApiClient {
  return new ApiClient(baseUrl);
}
`;
  }

  private renderClientMethod(route: RouteDefinition, name: string): string {
    const listReturn = `ApiResponse<${name}[]>`;
    const itemReturn = `ApiResponse<${name}>`;
    const basePath = route.path.replace("/:id", "");

    if (route.method === "GET" && !route.hasParam) {
      return `  async ${route.fnName}(): Promise<${listReturn}> {
    const res = await fetch(\`\${this.baseUrl}${basePath}\`);
    if (!res.ok) throw new Error(\`GET ${basePath} failed: \${res.status}\`);
    return res.json();
  }`;
    }

    if (route.method === "GET") {
      return `  async ${route.fnName}(id: string): Promise<${itemReturn}> {
    const res = await fetch(\`\${this.baseUrl}${basePath}/\${id}\`);
    if (!res.ok) throw new Error(\`GET ${basePath}/\${id} failed: \${res.status}\`);
    return res.json();
  }`;
    }

    if (route.method === "POST") {
      return `  async ${route.fnName}(body: Create${name}Dto): Promise<${itemReturn}> {
    const res = await fetch(\`\${this.baseUrl}${basePath}\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`POST ${basePath} failed: \${res.status}\`);
    return res.json();
  }`;
    }

    if (route.method === "PATCH") {
      return `  async ${route.fnName}(id: string, body: Update${name}Dto): Promise<${itemReturn}> {
    const res = await fetch(\`\${this.baseUrl}${basePath}/\${id}\`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!res.ok) throw new Error(\`PATCH ${basePath}/\${id} failed: \${res.status}\`);
    return res.json();
  }`;
    }

    // DELETE
    return `  async ${route.fnName}(id: string): Promise<ApiResponse<void>> {
    const res = await fetch(\`\${this.baseUrl}${basePath}/\${id}\`, { method: 'DELETE' });
    if (!res.ok) throw new Error(\`DELETE ${basePath}/\${id} failed: \${res.status}\`);
    return res.json();
  }`;
  }

  // ── .env.production ────────────────────────────────────────────────

  private generateEnvProduction(blueprint: BackendBlueprint, deploymentUrl?: string): string {
    const authProvider = blueprint.infrastructure?.auth?.provider;
    const hasAuth = !!authProvider && authProvider !== "Unknown";

    const paymentsProvider = blueprint.infrastructure?.payments?.provider;
    const hasStripe =
      (!!paymentsProvider && /stripe/i.test(paymentsProvider)) ||
      (blueprint.integrations ?? []).some((i) => /stripe/i.test(`${i.name} ${i.provider}`));

    const lines: string[] = [
      "# Generated by Simplicit — update BACKEND_URL after deploying to Railway/Render",
      `NEXT_PUBLIC_API_URL=${deploymentUrl || "https://your-backend.railway.app"}`,
      "",
      "# Add these to your Railway/Render environment variables:",
      "DATABASE_URL=",
    ];
    if (hasAuth) lines.push("JWT_SECRET=");
    if (hasStripe) lines.push("STRIPE_SECRET_KEY=");
    lines.push("CORS_ORIGIN=https://your-frontend-domain.com");
    lines.push("NODE_ENV=production");
    lines.push("PORT=3000");

    return lines.join("\n") + "\n";
  }

  // ── Derivations ────────────────────────────────────────────────────

  private getEntityFields(entity: BlueprintEntity): EntityFieldDef[] {
    return (entity.fields ?? []).map((f) => ({
      name: f.name,
      tsType: f.isNullable ? `${this.baseTsType(f.name, f.type)} | null` : this.baseTsType(f.name, f.type),
      optional: f.isNullable === true,
    }));
  }

  /**
   * Field type → TS type, mirroring DrizzleGenerator.mapType's vocabulary
   * first, then the name-based heuristics as fallback.
   */
  private baseTsType(name: string, type?: string): string {
    const t = (type ?? "").toLowerCase();
    if (["uuid", "varchar", "text", "string", "email", "slug", "url"].includes(t)) return "string";
    if (["integer", "int", "decimal", "number", "numeric", "float"].includes(t)) return "number";
    if (t === "boolean" || t === "bool") return "boolean";
    if (["timestamp", "date", "datetime"].includes(t)) return "string"; // ISO date string over JSON
    if (t === "jsonb" || t === "json") return "Record<string, unknown>";

    const lower = name.toLowerCase();
    if (lower === "id" || /id$/.test(lower)) return "string";
    if (/at$/.test(lower)) return "string"; // createdAt/updatedAt-style ISO strings
    if (/^(is|has)[a-z_]/i.test(name) || ["enabled", "verified", "active"].includes(lower)) return "boolean";
    if (["name", "title", "description", "email", "slug"].includes(lower)) return "string";
    if (["count", "amount", "price", "quantity", "total"].includes(lower)) return "number";
    return "unknown";
  }

  /**
   * Non-primary entities: list + create only. Primary (or undefined isPrimary —
   * the backend keeps full CRUD unless isPrimary === false): all five routes.
   * Resource segment = entity.tableName, the same value the backend serves.
   */
  private deriveRoutes(entity: BlueprintEntity, _blueprint: BackendBlueprint): RouteDefinition[] {
    const name = this.entityTypeName(entity);
    const resource = (entity.tableName || this.pluralKebab(entity.name)).toLowerCase();
    const base = `/${resource}`;
    const plural = name.endsWith("s") ? name : `${name}s`;
    const isPrimary = entity.isPrimary !== false;

    const routes: RouteDefinition[] = [
      { method: "GET", path: base, fnName: `get${plural}`, hasBody: false, hasParam: false, entityName: name },
      { method: "POST", path: base, fnName: `create${name}`, hasBody: true, hasParam: false, entityName: name },
    ];

    if (isPrimary) {
      routes.splice(1, 0, {
        method: "GET", path: `${base}/:id`, fnName: `get${name}ById`, hasBody: false, hasParam: true, entityName: name,
      });
      routes.push(
        { method: "PATCH", path: `${base}/:id`, fnName: `update${name}`, hasBody: true, hasParam: true, entityName: name },
        { method: "DELETE", path: `${base}/:id`, fnName: `delete${name}`, hasBody: false, hasParam: true, entityName: name },
      );
    }

    return routes;
  }

  private entityTypeName(entity: BlueprintEntity): string {
    const cleaned = entity.name.replace(/[^A-Za-z0-9_]/g, "");
    return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
  }

  private pluralKebab(name: string): string {
    const kebab = name
      .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .replace(/[\s_]+/g, "-")
      .toLowerCase();
    return kebab.endsWith("s") ? kebab : `${kebab}s`;
  }
}
