// StackForge Auth Pages — sign in, sign up, forgot password.
// Each is exported as a separate component for the canvas.

const { useState: aUseState } = React;

function AuthShell({ children, footnote }) {
  const Icons = window.Icons;
  return (
    <div className="sf-app" style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--sf-bg)' }}>
      {/* Left brand panel */}
      <div style={{
        flex: '1 1 0', minWidth: 0, position: 'relative', overflow: 'hidden',
        background: 'var(--sf-bg-2)', borderRight: '1px solid var(--sf-border)',
        display: 'flex', flexDirection: 'column', padding: 48,
      }}>
        <div className="sf-linegrid" style={{
          position: 'absolute', inset: 0, opacity: 0.55,
          maskImage: 'radial-gradient(ellipse 80% 70% at 30% 50%, black, transparent 80%)',
        }} />
        <div aria-hidden style={{
          position: 'absolute', left: '20%', top: '20%', width: 380, height: 380,
          background: 'radial-gradient(circle, oklch(0.4 0.12 250 / 0.32), transparent 70%)',
          filter: 'blur(40px)', pointerEvents: 'none',
        }} />
        <window.SFLogo />

        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', position: 'relative', maxWidth: 460 }}>
          <span className="sf-chip" style={{ alignSelf: 'flex-start', marginBottom: 22 }}>
            <span className="sf-dot sf-dot--green" /> v2.4 · Architect agents
          </span>
          <h1 style={{ fontSize: 42, lineHeight: 1.05, letterSpacing: '-0.03em', fontWeight: 500, margin: 0 }}>
            Backend foundations,<br/>generated by an AI architect.
          </h1>
          <p className="sf-muted" style={{ fontSize: 15, lineHeight: 1.55, marginTop: 18 }}>
            From a single prompt to a real, opinionated codebase you can defend in review.
          </p>

          {/* Mini code mock */}
          <div className="sf-card-elev" style={{ marginTop: 36, padding: 0, overflow: 'hidden' }}>
            <div className="sf-row" style={{ padding: '8px 14px', gap: 8, borderBottom: '1px solid var(--sf-border)', background: 'var(--sf-bg-2)' }}>
              <span className="sf-dot" style={{ background: '#3a3a3f' }} />
              <span className="sf-dot" style={{ background: '#3a3a3f' }} />
              <span className="sf-dot" style={{ background: '#3a3a3f' }} />
              <span className="mono sf-faint" style={{ fontSize: 10.5, marginLeft: 8 }}>routes.ts</span>
            </div>
            <window.CodeBlock language="ts" lines={window.SF_CODE_ROUTES.slice(0, 12)} height={180} scroll showLineNumbers />
          </div>
        </div>

        <div className="sf-row" style={{ gap: 12, color: 'var(--sf-text-faint)', fontSize: 12, position: 'relative' }}>
          <span>SOC 2 Type II</span>
          <span className="sf-faint">·</span>
          <span>Self-host the output</span>
          <span className="sf-faint">·</span>
          <span>MIT-licensed exports</span>
        </div>
      </div>

      {/* Right auth panel */}
      <div style={{ flex: '0 0 560px', maxWidth: '50%', padding: '60px 64px', display: 'flex', flexDirection: 'column', gap: 24 }}>
        <div className="sf-row" style={{ marginBottom: 20 }}>
          <span className="sf-grow" />
          <a className="sf-faint" style={{ fontSize: 12.5 }}>Need help? <span style={{ color: 'var(--sf-text)' }}>Contact us</span></a>
        </div>
        {children}
        {footnote}
      </div>
    </div>
  );
}

function OAuthRow() {
  const Icons = window.Icons;
  return (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
      <button className="sf-btn" style={{ justifyContent: 'center' }}><Icons.Github size={13} /> GitHub</button>
      <button className="sf-btn" style={{ justifyContent: 'center' }}>
        <svg width="13" height="13" viewBox="0 0 24 24"><path fill="currentColor" d="M21.6 11.3c0-.7-.1-1.3-.2-2H12v3.7h5.4c-.2 1.2-.9 2.2-2 2.9v2.4h3.2c1.9-1.7 3-4.3 3-7Z"/><path fill="currentColor" opacity=".7" d="M12 22c2.7 0 5-1 6.6-2.7l-3.2-2.4c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3.1v2.6A10 10 0 0 0 12 22Z"/><path fill="currentColor" opacity=".5" d="M6.4 13.8a6 6 0 0 1 0-3.6V7.6H3.1a10 10 0 0 0 0 8.8l3.3-2.6Z"/><path fill="currentColor" opacity=".3" d="M12 5.9c1.5 0 2.8.5 3.8 1.5l2.8-2.8A10 10 0 0 0 3.1 7.6l3.3 2.6C7.2 7.8 9.4 5.9 12 5.9Z"/></svg>
        Google
      </button>
      <button className="sf-btn" style={{ justifyContent: 'center' }}>
        <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M17.6 12.7c0-2.4 2-3.6 2-3.6-1.1-1.6-2.8-1.8-3.4-1.8-1.4-.2-2.8.9-3.5.9-.7 0-1.8-.8-3-.8-1.5 0-2.9.9-3.7 2.2-1.6 2.7-.4 6.7 1.1 8.9.7 1.1 1.6 2.3 2.8 2.3 1.1 0 1.5-.7 2.9-.7s1.7.7 2.9.7c1.2 0 2-1.1 2.7-2.2.8-1.3 1.2-2.5 1.2-2.6 0 0-2-.7-2-3.3ZM15.5 5.4c.6-.7 1-1.7.9-2.7-.9 0-2 .6-2.6 1.3-.6.6-1.1 1.6-1 2.6 1 .1 2-.5 2.7-1.2Z"/></svg>
        Apple
      </button>
    </div>
  );
}

const SignIn = () => {
  const Icons = window.Icons;
  return (
    <AuthShell footnote={
      <p className="sf-faint" style={{ fontSize: 12, textAlign: 'center', marginTop: 'auto' }}>
        By signing in you agree to our <span style={{ color: 'var(--sf-text-muted)' }}>Terms</span> and <span style={{ color: 'var(--sf-text-muted)' }}>Privacy Policy</span>.
      </p>
    }>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <h2 style={{ fontSize: 26, fontWeight: 500, letterSpacing: '-0.02em', margin: '0 0 6px' }}>Welcome back</h2>
        <p className="sf-muted" style={{ fontSize: 14, marginBottom: 28 }}>Sign in to your StackForge workspace.</p>

        <OAuthRow />
        <div className="sf-row" style={{ gap: 12, margin: '22px 0' }}>
          <div style={{ flex: 1, height: 1, background: 'var(--sf-border)' }} />
          <span className="mono sf-faint" style={{ fontSize: 10.5, letterSpacing: '0.08em', textTransform: 'uppercase' }}>or with email</span>
          <div style={{ flex: 1, height: 1, background: 'var(--sf-border)' }} />
        </div>

        <FormField label="Work email" value="alex@acmestudio.com" />
        <FormField label="Password" type="password" trailing={<a className="sf-faint" style={{ fontSize: 11.5 }}>Forgot?</a>} />

        <label className="sf-row" style={{ gap: 8, marginTop: 16, fontSize: 12.5, color: 'var(--sf-text-muted)' }}>
          <span style={{
            width: 14, height: 14, borderRadius: 3, background: 'var(--sf-text)',
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Icons.Check size={10} cls="" />
          </span>
          Keep me signed in for 30 days
        </label>

        <button className="sf-btn sf-btn--primary sf-btn--lg" style={{ width: '100%', justifyContent: 'center', marginTop: 24 }}>
          Sign in <Icons.ArrowR size={12} />
        </button>

        <p className="sf-muted" style={{ fontSize: 13, textAlign: 'center', marginTop: 22 }}>
          New here? <span style={{ color: 'var(--sf-text)', cursor: 'pointer' }}>Create an account</span>
        </p>
      </div>
    </AuthShell>
  );
};

const SignUp = () => {
  const Icons = window.Icons;
  return (
    <AuthShell>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <span className="sf-chip" style={{ alignSelf: 'flex-start', marginBottom: 14 }}>
          <span className="sf-dot sf-dot--green" /> Free during public beta
        </span>
        <h2 style={{ fontSize: 26, fontWeight: 500, letterSpacing: '-0.02em', margin: '0 0 6px' }}>Create your workspace</h2>
        <p className="sf-muted" style={{ fontSize: 14, marginBottom: 28 }}>Generate your first backend in under a minute.</p>

        <OAuthRow />
        <div className="sf-row" style={{ gap: 12, margin: '22px 0' }}>
          <div style={{ flex: 1, height: 1, background: 'var(--sf-border)' }} />
          <span className="mono sf-faint" style={{ fontSize: 10.5, letterSpacing: '0.08em', textTransform: 'uppercase' }}>or with email</span>
          <div style={{ flex: 1, height: 1, background: 'var(--sf-border)' }} />
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <FormField label="First name" value="Alex" />
          <FormField label="Last name" value="Chen" />
        </div>
        <FormField label="Work email" value="alex@acmestudio.com" />
        <FormField label="Password" type="password" hint="At least 12 characters" />

        <div className="sf-row" style={{ gap: 8, marginTop: 16, padding: 12, background: 'var(--sf-surface)', border: '1px solid var(--sf-border)', borderRadius: 8 }}>
          <Icons.Lock size={13} cls="sf-muted" />
          <span style={{ fontSize: 12, color: 'var(--sf-text-muted)' }}>
            Your prompts are private. We never train models on your generations.
          </span>
        </div>

        <button className="sf-btn sf-btn--primary sf-btn--lg" style={{ width: '100%', justifyContent: 'center', marginTop: 22 }}>
          Create workspace <Icons.ArrowR size={12} />
        </button>
        <p className="sf-muted" style={{ fontSize: 13, textAlign: 'center', marginTop: 18 }}>
          Already have an account? <span style={{ color: 'var(--sf-text)', cursor: 'pointer' }}>Sign in</span>
        </p>
      </div>
    </AuthShell>
  );
};

const ForgotPassword = () => {
  const Icons = window.Icons;
  return (
    <AuthShell>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
        <button className="sf-btn sf-btn--ghost sf-btn--sm" style={{ alignSelf: 'flex-start', marginBottom: 22, padding: '0 6px' }}>
          ← Back to sign in
        </button>
        <h2 style={{ fontSize: 26, fontWeight: 500, letterSpacing: '-0.02em', margin: '0 0 6px' }}>Reset your password</h2>
        <p className="sf-muted" style={{ fontSize: 14, marginBottom: 28 }}>
          We'll send a magic link to your work email — no password required.
        </p>

        <FormField label="Work email" value="alex@acmestudio.com" />

        <div className="sf-card" style={{ marginTop: 20, padding: 14, background: 'var(--sf-surface)' }}>
          <div className="sf-row" style={{ gap: 10, alignItems: 'flex-start' }}>
            <Icons.Info size={14} cls="sf-muted" />
            <div>
              <div style={{ fontSize: 12.5 }}>Magic links expire in 15 minutes</div>
              <div className="sf-faint" style={{ fontSize: 11.5, marginTop: 2 }}>
                The same link signs you in and resets your password.
              </div>
            </div>
          </div>
        </div>

        <button className="sf-btn sf-btn--primary sf-btn--lg" style={{ width: '100%', justifyContent: 'center', marginTop: 22 }}>
          Send magic link
        </button>
      </div>
    </AuthShell>
  );
};

function FormField({ label, type = 'text', value, hint, trailing }) {
  return (
    <div style={{ marginBottom: 14 }}>
      <div className="sf-row" style={{ marginBottom: 6 }}>
        <label style={{ fontSize: 12, color: 'var(--sf-text-muted)' }}>{label}</label>
        <span className="sf-grow" />
        {trailing}
      </div>
      <input className="sf-input" type={type} defaultValue={value} style={{ height: 38, fontSize: 13.5 }} />
      {hint && <div className="sf-faint" style={{ fontSize: 11.5, marginTop: 5 }}>{hint}</div>}
    </div>
  );
}

Object.assign(window, { SignIn, SignUp, ForgotPassword });
